"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { LogoMark } from "@/components/logo";
import { adminApi } from "@/lib/api";

export default function AdminLogin() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{await adminApi.login(email,password);window.location.href="/admin";}catch(error){setError(error instanceof Error?error.message:"Login failed");setLoading(false);}}
  return <main className="grid min-h-[100dvh] place-items-center bg-[#f4f1ea] p-5"><section className="w-full max-w-[410px] rounded-[26px] border border-[#dedfd9] bg-white p-7 shadow-soft sm:p-9"><LogoMark/><div className="mt-9"><div className="mb-4 grid h-11 w-11 place-items-center rounded-2xl bg-[#e4efe9] text-forest"><LockKeyhole size={19}/></div><h1 className="text-[24px] font-bold tracking-[-.04em]">Admin sign in</h1><p className="mt-2 text-[11px] leading-5 text-[#78837e]">Use your authorized Maqar administrator account.</p></div><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wide text-[#6f7b75]">Email</span><input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="h-12 w-full rounded-xl border border-[#d9dcd6] px-3 text-[12px] outline-none focus:border-[#7f9e91]"/></label><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wide text-[#6f7b75]">Password</span><input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-xl border border-[#d9dcd6] px-3 text-[12px] outline-none focus:border-[#7f9e91]"/></label>{error&&<p className="rounded-xl bg-[#fbe9e5] px-3 py-2 text-[9px] font-semibold text-[#9b4433]">{error}</p>}<button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-forest text-[11px] font-bold text-white disabled:opacity-60">{loading?"Signing in…":"Sign in"}<ArrowRight size={15}/></button></form></section></main>;
}
