"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
import { ArrowLeft,CheckCircle2,FileText,UploadCloud } from "lucide-react";
import { adminApi } from "@/lib/api";
type Knowledge={id:string;approvalStatus:string;createdAt:string;structured:any};type Item={id:string;category:string;content:string;approvalStatus:string};
export default function KnowledgePage({params}:{params:Promise<{id:string}>}){const[projectId,setProjectId]=useState("");const[text,setText]=useState("");const[knowledge,setKnowledge]=useState<Knowledge[]>([]);const[items,setItems]=useState<Item[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{params.then(x=>setProjectId(x.id))},[params]);const load=()=>{if(!projectId)return;Promise.all([adminApi.get<Knowledge[]>(`/projects/${projectId}/knowledge`),adminApi.get<Item[]>(`/projects/${projectId}/knowledge/items`)]).then(([a,b])=>{setKnowledge(a);setItems(b)}).catch(e=>setError(e.message))};useEffect(load,[projectId]);
  async function paste(e:FormEvent){e.preventDefault();setLoading(true);try{await adminApi.post(`/projects/${projectId}/knowledge/paste`,{text});setText("");load()}catch(e){setError(e instanceof Error?e.message:"Extraction failed")}finally{setLoading(false)}}
  async function upload(file?:File){if(!file)return;setLoading(true);try{const form=new FormData();form.append("file",file);await adminApi.upload(`/projects/${projectId}/knowledge/upload`,form);load()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setLoading(false)}}
  async function approve(id:string){await adminApi.post(`/projects/${projectId}/knowledge/${id}/approve`);load()}
  async function save(item:Item,content:string){await adminApi.patch(`/projects/${projectId}/knowledge/items/${item.id}`,{content,approvalStatus:item.approvalStatus});load()}
  return <main className="min-h-screen bg-[#f6f5f1] p-5 sm:p-8"><div className="mx-auto max-w-5xl"><a href="/admin/projects" className="flex items-center gap-2 text-[10px] font-bold"><ArrowLeft size={14}/> Projects</a><div className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.15em] text-coral">Verified knowledge</p><h1 className="mt-2 text-[28px] font-bold tracking-[-.04em]">Project knowledge</h1></div><input ref={fileRef} className="hidden" type="file" accept=".txt,.pdf,.docx" onChange={e=>upload(e.target.files?.[0])}/><button onClick={()=>fileRef.current?.click()} className="flex h-10 items-center gap-2 rounded-xl bg-forest px-4 text-[9px] font-bold text-white"><UploadCloud size={14}/> Upload TXT, PDF or DOCX</button></div>{error&&<div className="mt-4 rounded-xl bg-[#fbe9e5] p-3 text-[9px]">{error}</div>}<form onSubmit={paste} className="mt-6 rounded-[22px] border bg-white p-5"><label className="text-[10px] font-bold">Paste source information</label><textarea required minLength={20} value={text} onChange={e=>setText(e.target.value)} rows={6} className="mt-3 w-full resize-y rounded-xl border p-3 text-[10px] outline-none" placeholder="Paste developer-supplied project information. The original text is preserved."/><button disabled={loading} className="mt-3 h-10 rounded-xl bg-forest px-5 text-[9px] font-bold text-white">Extract for review</button></form><section className="mt-5 rounded-[22px] border bg-white p-5"><h2 className="text-[11px] font-bold">Extraction batches</h2><div className="mt-4 space-y-2">{knowledge.map(k=><div key={k.id} className="flex items-center gap-3 rounded-xl bg-[#f5f4ef] p-3"><FileText size={15}/><div className="flex-1"><p className="text-[9px] font-bold">{new Date(k.createdAt).toLocaleString()}</p><p className="text-[8px] text-[#89938f]">{k.approvalStatus}</p></div>{k.approvalStatus!=="APPROVED"&&<button onClick={()=>approve(k.id)} className="flex items-center gap-1 rounded-lg bg-[#e2f0e9] px-3 py-2 text-[8px] font-bold text-[#287458]"><CheckCircle2 size={12}/> Approve batch</button>}</div>)}</div></section><section className="mt-5 rounded-[22px] border bg-white p-5"><h2 className="text-[11px] font-bold">Extracted facts and provenance</h2><div className="mt-4 space-y-3">{items.map(item=><div key={item.id} className="rounded-xl border p-3"><div className="mb-2 flex items-center justify-between"><span className="text-[8px] font-bold uppercase text-coral">{item.category}</span><span className="text-[7px] font-bold text-[#7c8882]">{item.approvalStatus}</span></div><textarea defaultValue={item.content} onBlur={e=>e.target.value!==item.content&&save(item,e.target.value)} rows={2} className="w-full resize-y bg-transparent text-[9px] leading-4 outline-none"/></div>)}</div></section></div></main>}
