"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, ClipboardList, Home, Search } from "lucide-react";
import { adminApi, adminErrorMessage } from "@/lib/api";

type Requirement = { id:string; title:string; propertyType?:string|null; locations:string[]; bedrooms?:number|null; budgetMax?:number|null; currency?:string|null; status:string; matchCount:number; active:boolean; updatedAt:string; conversationId?:string|null; customer:{name?:string|null;phone?:string|null}; selectedUnit?:{externalUnitId:string;projectName:string}|null };
const status:Record<string,string>={OPEN:"مفتوح",MATCHED:"له نتائج",NEEDS_MATCH:"يحتاج مطابقة",HUMAN_REVIEW:"مراجعة بشرية"};

export default function RequirementsPage(){
  const [items,setItems]=useState<Requirement[]>([]),[query,setQuery]=useState(""),[error,setError]=useState("");
  useEffect(()=>{adminApi.get<Requirement[]>("/conversations/workflow/requirements").then(setItems).catch((e)=>setError(adminErrorMessage(e)));},[]);
  const filtered=items.filter((item)=>[item.title,item.customer.name,item.customer.phone,...item.locations].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase()));
  return <main className="mx-auto max-w-[1480px] p-4 sm:p-6" dir="rtl">
    <header className="flex flex-col gap-4 rounded-[22px] border border-[#dfe4e0] bg-white p-5 md:flex-row md:items-end md:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold text-[#39705e]"><ClipboardList size={16}/>مساحة عمل المتطلبات</p><h1 className="mt-2 text-2xl font-extrabold">المتطلبات العقارية</h1><p className="mt-1 text-sm text-[#6d7b75]">طلب مستقل لكل احتياج، مع النتائج والوحدة المختارة وآخر بحث.</p></div><label className="relative block w-full md:max-w-sm"><span className="sr-only">بحث</span><Search className="absolute right-3 top-3.5 text-[#829089]" size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} className="h-11 w-full rounded-xl border bg-[#fafbf9] pr-10 pl-3 text-sm" placeholder="ابحث بالعميل أو المنطقة"/></label></header>
    {error?<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>:null}
    <section className="mt-4 overflow-hidden rounded-[22px] border bg-white"><div className="hidden grid-cols-[1.1fr_1.2fr_.8fr_.7fr_.65fr_.8fr_auto] gap-3 border-b bg-[#f8faf8] px-5 py-3 text-xs font-bold text-[#68766f] lg:grid"><span>العميل</span><span>الطلب</span><span>المنطقة</span><span>الميزانية</span><span>المطابقات</span><span>الوحدة المختارة</span><span/></div>{filtered.map((item)=><article key={item.id} className="grid gap-3 border-b px-5 py-4 last:border-0 lg:grid-cols-[1.1fr_1.2fr_.8fr_.7fr_.65fr_.8fr_auto] lg:items-center"><div><b className="text-sm">{item.customer.name||"عميل بدون اسم"}</b><p className="mt-1 text-xs text-[#75827c]" dir="ltr">{item.customer.phone||"—"}</p></div><div><p className="flex items-center gap-2 text-sm font-bold">{item.active?<CheckCircle2 size={15} className="text-emerald-600"/>:null}{item.title}</p><p className="mt-1 text-xs text-[#75827c]">{[item.propertyType,item.bedrooms?`${item.bedrooms} غرف`:null,status[item.status]||item.status].filter(Boolean).join(" · ")}</p></div><p className="text-sm">{item.locations.join("، ")||"—"}</p><p className="text-sm font-bold">{item.budgetMax?`${Number(item.budgetMax).toLocaleString("ar-EG")} ${item.currency||""}`:"—"}</p><span className="w-fit rounded-lg bg-[#edf4f0] px-2.5 py-1 text-xs font-bold">{item.matchCount}</span><p className="text-xs">{item.selectedUnit?<><b>{item.selectedUnit.projectName}</b><span className="block text-[#75827c]" dir="ltr">{item.selectedUnit.externalUnitId}</span></>:"—"}</p>{item.conversationId?<a href={`/admin/conversations/${item.conversationId}`} className="inline-flex min-h-11 items-center gap-1 text-xs font-bold text-[#28604f]">فتح المحادثة<ArrowLeft size={14}/></a>:null}</article>)}{!filtered.length?<div className="p-12 text-center"><Home className="mx-auto text-[#8b9791]"/><p className="mt-3 text-sm text-[#68766f]">لا توجد متطلبات عقارية مطابقة.</p></div>:null}</section>
  </main>;
}
