"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, CalendarClock, MessageCircle } from "lucide-react";
import { adminApi, adminErrorMessage } from "@/lib/api";

type FollowUp={id:string;dueAt:string;timezone:string;channel:string;status:string;reason:string;conversationId:string;customer:{name?:string|null;normalizedPhone?:string|null};propertyRequirement?:{title:string}|null;conversation:{mode:string}};
const fmt=(value:string)=>new Intl.DateTimeFormat("ar-EG",{dateStyle:"full",timeStyle:"short"}).format(new Date(value));
export default function FollowUpsPage(){const [items,setItems]=useState<FollowUp[]>([]),[error,setError]=useState("");useEffect(()=>{adminApi.get<FollowUp[]>("/conversations/workflow/follow-ups").then(setItems).catch((e)=>setError(adminErrorMessage(e)));},[]);return <main className="mx-auto max-w-[1280px] p-4 sm:p-6" dir="rtl"><header className="rounded-[22px] border bg-white p-5"><p className="flex items-center gap-2 text-xs font-bold text-[#39705e]"><CalendarClock size={16}/>جدول المتابعات</p><h1 className="mt-2 text-2xl font-extrabold">المتابعات القادمة</h1><p className="mt-1 text-sm text-[#6d7b75]">الموعد والقناة وحالة ملكية المحادثة ظاهرة قبل التنفيذ.</p></header>{error?<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>:null}<section className="mt-4 grid gap-3">{items.map((item)=><article key={item.id} className="grid gap-4 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_1fr_.7fr_auto] md:items-center"><div><b>{item.customer.name||"عميل بدون اسم"}</b><p className="mt-1 text-xs text-[#74817b]" dir="ltr">{item.customer.normalizedPhone||"—"}</p></div><div><p className="text-sm font-bold">{fmt(item.dueAt)}</p><p className="mt-1 text-xs text-[#74817b]">{item.timezone}</p></div><div><span className="inline-flex items-center gap-1 rounded-lg bg-[#edf4f0] px-2 py-1 text-xs font-bold"><MessageCircle size={13}/>{item.channel}</span><p className="mt-2 text-xs">{item.propertyRequirement?.title||item.reason}</p></div><a href={`/admin/conversations/${item.conversationId}`} className="inline-flex min-h-11 items-center gap-1 text-xs font-bold text-[#28604f]">فتح المحادثة<ArrowLeft size={14}/></a></article>)}{!items.length?<div className="rounded-2xl border bg-white p-12 text-center text-sm text-[#6d7b75]">لا توجد متابعات معلّقة. ستظهر هنا المهام التي أنشأها Nadim أو الفريق.</div>:null}</section></main>}
