"use client";
import { FormEvent, useEffect, useState } from "react";
import { adminApi, adminErrorMessage } from "@/lib/api";

type Portfolio = { id: string; projectName: string; status: string; locationText?: string | null; launchYear?: number | null; deliveryYear?: number | null; description?: string | null };
type Developer = { id: string; name: string; canonicalName?: string | null; nameAr?: string | null; nameEn?: string | null; brandName?: string | null; website?: string | null; foundedYear?: number | null; headquarters?: string | null; country?: string | null; developerType?: string | null; salesPhone?: string | null; email?: string | null; shortDescriptionAr?: string | null; shortDescriptionEn?: string | null; fullDescriptionAr?: string | null; fullDescriptionEn?: string | null; yearsInMarket?: number | null; deliveredProjectsCount?: number | null; projectsUnderConstructionCount?: number | null; geographicFocus: string[]; specialties: string[]; portfolioProjects: Portfolio[]; projects: { id: string; name: string; adminStatus: string }[]; media: Array<{id:string;url:string;altText?:string|null;isCover:boolean}> };
const array = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map(x => x.trim()).filter(Boolean);
export default function DeveloperDetails({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""), [item, setItem] = useState<Developer | null>(null), [error, setError] = useState(""), [saved, setSaved] = useState(false);
  useEffect(() => { params.then(({ id }) => { setId(id); adminApi.get<Developer>(`/real-estate/developers/${id}`).then(setItem).catch(error => setError(adminErrorMessage(error))); }); }, [params]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const f = new FormData(formElement); const data: Record<string, any> = Object.fromEntries(f); for (const key of ["foundedYear", "yearsInMarket", "deliveredProjectsCount", "projectsUnderConstructionCount"]) if (data[key] === "") delete data[key]; else data[key] = Number(data[key]); data.geographicFocus = array(f.get("geographicFocus")); data.specialties = array(f.get("specialties")); try { const updated = await adminApi.patch<Developer>(`/real-estate/developers/${id}`, data); setItem(current => current ? { ...current, ...updated } : current); setSaved(true); } catch (error) { setError(adminErrorMessage(error)); } }
  async function portfolio(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const f = new FormData(formElement); const data: Record<string, unknown> = Object.fromEntries(f); for (const key of ["launchYear", "deliveryYear", "unitsCount"]) if (!data[key]) delete data[key]; else data[key] = Number(data[key]); try { await adminApi.post(`/real-estate/developers/${id}/portfolio`, data); const refreshed = await adminApi.get<Developer>(`/real-estate/developers/${id}`); setItem(refreshed); formElement.reset(); } catch (error) { setError(adminErrorMessage(error)); } }
  async function uploadMedia(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);form.append("developerId",id);form.append("type","IMAGE");try{await adminApi.upload("/catalog/media",form);setItem(await adminApi.get<Developer>(`/real-estate/developers/${id}`));formElement.reset()}catch(error){setError(adminErrorMessage(error))}}
  if (!item) return <main className="p-8" dir="rtl">{error || "جارٍ التحميل…"}</main>;
  const textFields: Array<[keyof Developer, string]> = [["canonicalName","الاسم المعتمد"],["nameAr","الاسم بالعربية"],["nameEn","الاسم بالإنجليزية"],["brandName","العلامة التجارية"],["website","الموقع الإلكتروني"],["headquarters","المقر الرئيسي"],["country","الدولة"],["developerType","نوع المطور"],["salesPhone","هاتف المبيعات"],["email","البريد الإلكتروني"]];
  return <main className="mx-auto max-w-7xl p-4 sm:p-8" dir="rtl"><a href="/admin/developers" className="text-sm text-forest">← المطورون</a><h1 className="mt-3 text-2xl font-bold" dir="auto">{item.brandName || item.name}</h1>{error && <div className="mt-4 rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}
    <form onSubmit={save} className="mt-6 space-y-5"><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">الهوية والحضور العام</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{textFields.map(([key,label]) => <label key={key} className="text-sm">{label}<input name={key} defaultValue={String(item[key] ?? "")} className="mt-1 h-11 w-full rounded-xl border px-3" dir="auto"/></label>)}<label className="text-sm">سنة التأسيس<input name="foundedYear" type="number" defaultValue={item.foundedYear ?? ""} className="mt-1 h-11 w-full rounded-xl border px-3"/></label></div></section>
      <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">الوصف المنظم</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["shortDescriptionAr","نبذة عربية"],["shortDescriptionEn","نبذة إنجليزية"],["fullDescriptionAr","وصف عربي كامل"],["fullDescriptionEn","وصف إنجليزي كامل"]].map(([key,label]) => <label key={key} className="text-sm">{label}<textarea name={key} defaultValue={String(item[key as keyof Developer] ?? "")} className="mt-1 min-h-24 w-full rounded-xl border p-3" dir="auto"/></label>)}</div></section>
      <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">المؤشرات الموثقة</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["yearsInMarket","سنوات الخبرة"],["deliveredProjectsCount","المشروعات المسلمة"],["projectsUnderConstructionCount","تحت الإنشاء"]].map(([key,label]) => <label key={key} className="text-sm">{label}<input name={key} type="number" min="0" defaultValue={String(item[key as keyof Developer] ?? "")} className="mt-1 h-11 w-full rounded-xl border px-3"/></label>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">الانتشار الجغرافي (بفواصل)<input name="geographicFocus" defaultValue={item.geographicFocus.join(", ")} className="mt-1 h-11 w-full rounded-xl border px-3"/></label><label className="text-sm">التخصصات (بفواصل)<input name="specialties" defaultValue={item.specialties.join(", ")} className="mt-1 h-11 w-full rounded-xl border px-3"/></label></div></section>
      <button className="h-11 rounded-xl bg-forest px-6 font-bold text-white">حفظ بيانات المطور</button>{saved && <span className="mr-3 text-sm text-green-700">تم الحفظ</span>}
    </form>
    <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">السجل السابق والحالي</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{item.portfolioProjects.map(p => <div key={p.id} className="rounded-xl border p-4"><p className="font-bold" dir="auto">{p.projectName}</p><p className="mt-1 text-xs text-[#68756f]">{p.status} · {p.locationText || "الموقع غير محدد"}</p></div>)}</div><form onSubmit={portfolio} className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-3"><input required name="projectName" placeholder="اسم المشروع" className="h-11 rounded-xl border px-3"/><select required name="status" className="h-11 rounded-xl border px-3"><option value="">الحالة</option><option value="DELIVERED">تم التسليم</option><option value="UNDER_CONSTRUCTION">تحت الإنشاء</option><option value="UPCOMING">قادم</option><option value="HISTORICAL">تاريخي</option></select><input name="locationText" placeholder="الموقع" className="h-11 rounded-xl border px-3"/><input name="launchYear" type="number" placeholder="سنة الإطلاق" className="h-11 rounded-xl border px-3"/><input name="deliveryYear" type="number" placeholder="سنة التسليم" className="h-11 rounded-xl border px-3"/><button className="h-11 rounded-xl border border-forest font-bold text-forest">إضافة للسجل</button></form></section>
    <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">الشعار والوسائط</h2><div className="mt-4 flex flex-wrap gap-3">{item.media.map(media=><img key={media.id} src={media.url} alt={media.altText||"شعار المطور"} className="h-24 w-24 rounded-xl border object-contain"/>)}</div><form onSubmit={uploadMedia} className="mt-4 flex flex-wrap gap-2 border-t pt-4"><input required type="file" name="file" accept="image/*" className="rounded-xl border p-2 text-sm"/><input name="altText" placeholder="وصف الشعار أو الصورة" className="h-11 flex-1 rounded-xl border px-3"/><button className="h-11 rounded-xl border border-forest px-5 font-bold text-forest">رفع صورة</button></form></section>
  </main>;
}
