"use client";

import { useEffect, useState } from "react";
import { ArrowRight, Bot, CalendarClock, ExternalLink, Link2, MessageSquareText, Pause, RotateCcw, Send, Trash2, UserRound, UsersRound } from "lucide-react";
import { adminApi, adminErrorMessage } from "@/lib/api";

const labels: Record<string, string> = { OPEN: "مفتوح", MATCHED: "له نتائج", NEEDS_MATCH: "يحتاج مطابقة", HUMAN_REVIEW: "مراجعة بشرية", CLOSED: "مغلق", PENDING: "مجدولة", CLAIMED: "قيد الإرسال" };
const fmt = (value: string) => new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export default function ConversationDetail({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [item, setItem] = useState<any>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState(""); const [reply, setReply] = useState("");
  async function load(value: string) { try { setItem(await adminApi.get(`/conversations/${value}`)); } catch (e) { setError(adminErrorMessage(e)); } }
  useEffect(() => { params.then(({ id: value }) => { setId(value); void load(value); }); }, [params]);
  async function mode(value: "AI" | "HUMAN" | "PAUSED") { setBusy("mode"); setError(""); try { await adminApi.patch(`/conversations/${id}/mode`, { mode: value }); await load(id); setNotice(value === "AI" ? "عاد نديم لملكية المحادثة." : value === "HUMAN" ? "انتقلت المحادثة للفريق البشري." : "تم إيقاف الردود مؤقتًا."); } catch (e) { setError(adminErrorMessage(e)); } finally { setBusy(""); } }
  async function link(kind: "share" | "whatsapp") { setBusy(kind); setError(""); try { const result = await adminApi.post<{url:string}>(`/conversations/${id}/${kind}`); await navigator.clipboard.writeText(result.url); setNotice(kind === "share" ? "تم نسخ رابط المحادثة الآمن." : "تم نسخ رابط المتابعة على واتساب."); } catch (e) { setError(adminErrorMessage(e)); } finally { setBusy(""); } }
  async function remove() { if (!window.confirm("حذف هذه المحادثة سيلغي المتابعات المعلقة. هل أنت متأكد؟")) return; setBusy("delete"); try { await adminApi.delete(`/conversations/${id}`, { confirmation: "DELETE" }); window.location.href = "/admin/conversations"; } catch (e) { setError(adminErrorMessage(e)); setBusy(""); } }
  async function sendReply() { const content = reply.trim(); if (!content) return; setBusy("reply"); setError(""); try { await adminApi.post(`/conversations/${id}/messages`, { content }); setReply(""); await load(id); setNotice("تم إرسال رد الفريق وحفظه في نفس المحادثة."); } catch (e) { setError(adminErrorMessage(e)); } finally { setBusy(""); } }
  if (!item) return <main className="mx-auto max-w-[1180px] p-6" dir="rtl"><div className="rounded-2xl border bg-white p-8 text-center text-sm text-[#7b8781]">{error || "جارٍ تحميل المحادثة…"}</div></main>;
  return <main className="mx-auto max-w-[1240px] p-4 sm:p-6 lg:p-8" dir="rtl">
    <a href="/admin/conversations" className="inline-flex min-h-11 items-center gap-2 text-xs font-bold text-[#547267]"><ArrowRight size={15}/>الرجوع للمحادثات</a>
    <header className="rounded-[24px] border border-[#dfe4e0] bg-white p-5 sm:p-6">
      <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><p className="flex items-center gap-2 text-xs font-bold text-[#4f7568]"><MessageSquareText size={15}/> مساحة خدمة العميل</p><h1 className="mt-2 text-2xl font-bold" dir="auto">{item.identity}</h1><p className="mt-1 text-xs text-[#7b8781]">{item.channel} · {item.locale ?? "لغة غير محددة"} · {item.timezone ?? "منطقة زمنية غير محددة"} · آخر نشاط {fmt(item.updatedAt)}</p></div>
        <div className="flex flex-wrap gap-2"><Action onClick={()=>void mode("HUMAN")} disabled={!!busy} icon={<UsersRound size={15}/>} label="تسليم لبشري"/><Action onClick={()=>void mode("AI")} disabled={!!busy} primary icon={<RotateCcw size={15}/>} label="إعادة لنديم"/><Action onClick={()=>void mode("PAUSED")} disabled={!!busy} icon={<Pause size={15}/>} label="إيقاف"/></div></div>
      <div className="mt-5 flex flex-wrap items-center gap-2 border-t pt-4"><span className="ml-auto rounded-lg bg-[#edf3f0] px-3 py-1.5 text-xs font-bold">الملكية: {item.mode === "AI" ? "نديم" : item.mode === "HUMAN" ? "الفريق البشري" : "متوقفة"}</span><Action onClick={()=>void link("share")} disabled={!!busy} icon={<Link2 size={15}/>} label="نسخ رابط آمن"/><Action onClick={()=>void link("whatsapp")} disabled={!!busy} icon={<ExternalLink size={15}/>} label="متابعة على واتساب"/><button onClick={()=>void remove()} disabled={!!busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-red-200 px-3 text-xs font-bold text-red-700 disabled:opacity-50"><Trash2 size={15}/>حذف</button></div>
      {notice ? <p className="mt-3 text-xs font-semibold text-emerald-800" aria-live="polite">{notice}</p> : null}{error ? <p className="mt-3 text-xs text-red-700" role="alert">{error}</p> : null}
    </header>
    <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
      <section aria-label="نص المحادثة" className="space-y-3">{item.messages?.map((message:any)=><article key={message.id} className={`flex gap-3 ${message.role === "USER" ? "" : "flex-row-reverse"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${message.role === "USER" ? "border bg-white text-[#46645a]" : message.role === "HUMAN" ? "bg-[#8a5b24] text-white" : "bg-[#123c33] text-white"}`}>{message.role === "USER" ? <UserRound size={16}/> : message.role === "HUMAN" ? <UsersRound size={16}/> : <Bot size={16}/>}</span><div dir="auto" className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-7 ${message.role === "USER" ? "border bg-white" : message.role === "HUMAN" ? "border border-amber-200 bg-amber-50 text-[#3b2a16]" : "bg-[#e8f0ec] text-[#17251f]"}`}><p className="whitespace-pre-wrap">{message.content}</p><p className="mt-2 text-[11px] text-[#75837c]">{message.role === "HUMAN" ? "رد الفريق البشري" : message.channel} · {fmt(message.createdAt)}</p></div></article>)}{!item.messages?.length ? <Empty text="لا توجد رسائل بعد."/> : null}{item.mode === "HUMAN" ? <div className="sticky bottom-4 rounded-2xl border border-[#d6ddd9] bg-white p-3 shadow-lg"><label htmlFor="human-reply" className="mb-2 block text-xs font-bold text-[#425b52]">رد الفريق على العميل</label><div className="flex items-end gap-2"><textarea id="human-reply" value={reply} onChange={(event)=>setReply(event.target.value)} rows={2} dir="auto" placeholder="اكتب ردًا بشريًا واضحًا…" className="min-h-12 flex-1 resize-y rounded-xl border border-[#d8dfdb] px-3 py-2 text-sm outline-none focus:border-[#557d6f]"/><button onClick={()=>void sendReply()} disabled={busy === "reply" || !reply.trim()} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#173f3b] text-white disabled:opacity-40" aria-label="إرسال رد الفريق"><Send size={17}/></button></div></div> : null}</section>
      <aside className="space-y-4">
        <Panel title="متطلبات العقار">{item.propertyRequirements?.length ? item.propertyRequirements.map((r:any)=><div key={r.id} className={`rounded-xl border p-3 ${r.active ? "border-[#6f9588] bg-[#f3f8f5]" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><b className="text-[13px]" dir="auto">{r.title}</b><span className="shrink-0 rounded-md bg-white px-2 py-1 text-[10px] font-bold">{labels[r.status] ?? r.status}</span></div><p className="mt-2 text-xs leading-5 text-[#65736d]" dir="auto">{[r.propertyType, r.bedrooms ? `${r.bedrooms} غرف` : null, ...(r.locations ?? []), r.budgetMax ? `حتى ${Number(r.budgetMax).toLocaleString("ar-EG")} ${r.currency ?? ""}` : null].filter(Boolean).join(" · ")}</p></div>) : <Empty text="لا توجد متطلبات عقارية."/>}</Panel>
        <Panel title="المتابعات">{item.followUpTasks?.length ? item.followUpTasks.map((task:any)=><div key={task.id} className="rounded-xl bg-sky-50 p-3"><p className="flex items-center gap-2 text-xs font-bold text-sky-900"><CalendarClock size={14}/>{fmt(task.dueAt)}</p><p className="mt-1 text-[11px] text-sky-800" dir="auto">{task.reason} · {labels[task.status] ?? task.status}</p></div>) : <Empty text="لا توجد متابعات معلقة."/>}</Panel>
        <Panel title="المشاركون والقنوات">{item.participants?.length ? item.participants.map((p:any)=><div key={p.id} className="flex items-center justify-between gap-2 py-2 text-xs"><span dir="auto">{p.externalUserId}</span><span className="text-[#74817b]">{p.channel} · {p.role === "OWNER" ? "مالك" : "مشارك"}</span></div>) : <Empty text="لا يوجد مشاركون مسجلون."/>}</Panel>
        {item.customerContext ? <Panel title="سياق العميل"><pre className="whitespace-pre-wrap break-words font-sans text-xs leading-6 text-[#52635c]" dir="auto">{Object.entries(item.customerContext).map(([key,value])=>`${key}: ${String(value)}`).join("\n")}</pre></Panel> : null}
      </aside>
    </div>
  </main>;
}

function Action({ onClick, disabled, icon, label, primary = false }: { onClick:()=>void; disabled:boolean; icon:React.ReactNode; label:string; primary?:boolean }) { return <button onClick={onClick} disabled={disabled} className={`inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-xs font-bold disabled:opacity-50 ${primary ? "bg-[#173f3b] text-white" : "border"}`}>{icon}{label}</button>; }
function Panel({ title, children }: { title:string; children:React.ReactNode }) { return <section className="rounded-[20px] border border-[#dfe4e0] bg-white p-4"><h2 className="mb-3 text-sm font-bold">{title}</h2><div className="space-y-2">{children}</div></section>; }
function Empty({ text }: { text:string }) { return <p className="rounded-xl bg-[#f7f8f6] p-3 text-xs text-[#74817b]">{text}</p>; }
