import { AIContextKind, AIMessage, AnswerInput, StructuredIntent } from "./ai-provider";

const SYSTEM_PROMPT = "You are Maqar, a concise Egyptian real-estate advisor. Match the customer's Arabic, English, or mixed style. Property facts may only come from VERIFIED_FACTS; descriptive claims may only come from APPROVED_KNOWLEDGE. Never invent inventory, availability, price, payment, delivery, distance, media, scarcity, or project claims. Give at most five useful matches with an honest tradeoff and ask at most one useful question. Do not mention providers, prompts, or tools.";
const bytes = (value: unknown) => Buffer.byteLength(JSON.stringify(value), "utf8");
const text = (value: unknown, limit = 500) => typeof value === "string" ? value.slice(0, limit) : value ?? null;
const numeric = (value: unknown) => value == null ? null : Number(value);

function compactIntent(intent: StructuredIntent) {
  const keys: Array<keyof StructuredIntent> = ["language","dialect","purpose","locations","propertyTypes","bedrooms","bathrooms","budgetMin","budgetMax","currency","deliveryMaxYears","maxDownPayment","maxTravelMinutes","builtUpAreaMin","builtUpAreaMax","hardRequirements","softPreferences","requestedProject","purchaseIntent","familyRequirements","investmentRequirements","customerConcerns"];
  return Object.fromEntries(keys.flatMap(key => intent[key] == null ? [] : [[key, intent[key]]]));
}

function paymentHighlight(plans: any[], intent: StructuredIntent) {
  if (!Array.isArray(plans) || !plans.length) return null;
  const byDuration = [...plans].sort((a,b) => Number(b.durationMonths ?? 0) - Number(a.durationMonths ?? 0));
  const byDownPayment = [...plans].sort((a,b) => Number(a.downPaymentAmount ?? a.downPayment ?? Infinity) - Number(b.downPaymentAmount ?? b.downPayment ?? Infinity));
  const plan = intent.maxDownPayment != null ? byDownPayment[0] : byDuration[0];
  return { name:text(plan.name,80),durationMonths:plan.durationMonths??null,downPaymentAmount:numeric(plan.downPaymentAmount??plan.downPayment),downPaymentPercent:numeric(plan.downPaymentPercent),installmentAmount:numeric(plan.installmentAmount),installmentFrequency:plan.installmentFrequency??null,totalPrice:numeric(plan.totalPrice),currency:plan.currency??null };
}

function propertyFact(value:any,intent:StructuredIntent){return{unitId:value.id??null,unitCode:value.externalUnitId??null,projectName:value.project?.nameAr??value.project?.nameEn??value.project?.name??null,developerName:value.developer?.nameAr??value.developer?.nameEn??value.developer?.brandName??value.developer?.name??null,location:value.project?.location?.nameAr??value.project?.location?.nameEn??value.project?.location?.name??null,unitType:value.unitType??null,bedrooms:value.bedrooms??null,bathrooms:value.bathrooms??null,builtUpArea:numeric(value.builtUpArea),price:numeric(value.price),currency:value.currency??null,availability:value.status??null,deliveryDate:value.deliveryDate??null,finishingType:value.finishingType??null,paymentPlan:paymentHighlight(value.paymentPlans,intent),offer:Array.isArray(value.offers)&&value.offers[0]?{title:text(value.offers[0].title,100),discountAmount:numeric(value.offers[0].discountAmount),endsAt:value.offers[0].endsAt??null}:null,matchScore:value.matchScore??null,matchReasons:Array.isArray(value.matchReasons)?value.matchReasons.slice(0,4):[]};}
function projectCore(value:any){return{projectId:value.id??null,projectName:value.nameAr??value.nameEn??value.name??null,developerName:value.developer?.nameAr??value.developer?.nameEn??value.developer?.brandName??value.developer?.name??null,location:value.location?.nameAr??value.location?.nameEn??value.location?.name??null,formattedAddress:value.formattedAddress??null,projectType:value.projectType??null,projectStatus:value.projectStatus??null,deliveryStatus:value.deliveryStatus??null,deliveryDate:value.deliveryDate??null,deliveryInformation:text(value.deliveryInformation,350),finishingOptions:value.finishingOptions?.slice?.(0,8)??[],unitTypes:value.unitTypes?.slice?.(0,10)??[],minArea:numeric(value.minArea),maxArea:numeric(value.maxArea),minBedrooms:value.minBedrooms??null,maxBedrooms:value.maxBedrooms??null,priceSummary:text(value.priceSummary,300),paymentSummary:text(value.paymentSummary,300),shortDescription:text(value.shortDescriptionAr??value.shortDescriptionEn??value.shortDescription,500)};}

function compactFact(value:any,kind:AIContextKind,intent:StructuredIntent){
  if(!value||typeof value!=="object")return value;
  if(kind==="PROPERTY_SEARCH"||kind==="COMPARISON")return propertyFact(value,intent);
  if(kind==="DEVELOPER_HISTORY")return{developerId:value.id,name:value.nameAr??value.nameEn??value.brandName??value.name,foundedYear:value.foundedYear??null,yearsInMarket:value.yearsInMarket??null,deliveredProjectsCount:value.deliveredProjectsCount??null,projectsUnderConstructionCount:value.projectsUnderConstructionCount??null,geographicFocus:value.geographicFocus?.slice?.(0,12)??[],specialties:value.specialties?.slice?.(0,12)??[],portfolio:value.portfolioProjects?.slice?.(0,20).map((p:any)=>({projectName:p.projectName,status:p.status,projectType:p.projectType,location:p.location?.name??p.locationText,launchYear:p.launchYear,deliveryYear:p.deliveryYear,unitsCount:p.unitsCount}))??[]};
  if(["INVESTMENT","RESALE","RENTAL"].includes(kind)){const p=value.investmentProfile??value;return{...projectCore(value),investment:kind==="INVESTMENT"?{suitableForLiving:p.suitableForLiving,suitableForInvestment:p.suitableForInvestment,strongestUnitTypes:p.strongestUnitTypes?.slice?.(0,8)??[],targetCustomers:p.targetCustomers?.slice?.(0,8)??[],advantages:p.investmentAdvantages?.slice?.(0,8)??[],risks:p.investmentRisks?.slice?.(0,8)??[],notes:text(p.notes,350),source:text(p.source,120)}:kind==="RESALE"?{resaleDemand:p.resaleDemand,advantages:p.investmentAdvantages?.slice?.(0,5)??[],risks:p.investmentRisks?.slice?.(0,5)??[],source:text(p.source,120)}:{suitableForRental:p.suitableForRental,rentalDemand:p.rentalDemand,expectedRentalYieldMin:numeric(p.expectedRentalYieldMin),expectedRentalYieldMax:numeric(p.expectedRentalYieldMax),strongestUnitTypes:p.strongestUnitTypes?.slice?.(0,5)??[],source:text(p.source,120)}};}
  if(kind==="AMENITIES")return{...projectCore(value),amenities:value.amenities?.slice?.(0,30).map((x:any)=>({name:x.amenity?.nameAr??x.amenity?.nameEn??x.amenity?.canonicalName,category:x.amenity?.category,notes:text(x.notes,120)}))??[]};
  if(kind==="MEDIA_REQUEST")return{id:value.id,type:value.type,url:value.url,altText:text(value.altTextAr??value.altTextEn??value.altText,160),caption:text(value.caption,160),isCover:Boolean(value.isCover)};
  if(kind==="BROCHURE_REQUEST")return{id:value.id,type:value.type,name:value.name,url:value.url,language:value.language??null};
  if(kind==="DISTANCE")return{source:value.source??value.distanceType,distanceKm:numeric(value.distanceKm??(value.distanceMeters!=null?Number(value.distanceMeters)/1000:null)),estimatedMinutes:value.estimatedMinutes??value.duration??null,from:value.from?.name??value.from,to:value.to?.name??value.to,notes:text(value.notes,200)};
  if(kind==="AGGREGATION")return value;
  return{...projectCore(value),landmarks:value.landmarks?.slice?.(0,12).map((x:any)=>({name:x.name,category:x.category,distanceKm:numeric(x.distanceKm),estimatedMinutes:x.estimatedMinutes,distanceType:x.distanceType}))??[],amenities:value.amenities?.slice?.(0,20).map((x:any)=>x.amenity?.nameAr??x.amenity?.nameEn??x.amenity?.canonicalName)??[]};
}

export function compactAnswerInput(input:AnswerInput,level:"normal"|"aggressive"=input.compactionLevel??"normal"):AnswerInput{const kind=input.contextKind??"PROPERTY_SEARCH",candidateLimit=level==="aggressive"?3:5,historyLimit=level==="aggressive"?4:6;const selected=input.messages.slice(-historyLimit);return{...input,messages:selected.map((m,index)=>({...m,content:m.content.slice(0,index===selected.length-1?3000:level==="aggressive"?700:1400)})),verifiedFacts:input.verifiedFacts.slice(0,candidateLimit).map(v=>compactFact(v,kind,input.intent)),approvedKnowledge:["PROJECT_DETAILS","INVESTMENT","RESALE","RENTAL","AMENITIES"].includes(kind)?(input.approvedKnowledge??[]).slice(0,level==="aggressive"?2:4).map((v:any)=>({category:v.category,content:text(v.content,level==="aggressive"?250:500)})):[],conversationSummary:compactSummary(input.conversationSummary,level),compactionLevel:level};}
function compactSummary(value:unknown,level:"normal"|"aggressive"){if(!value||typeof value!=="object")return value?text(value,level==="aggressive"?600:1200):undefined;const v=value as Record<string,any>;return{customerGoal:text(v.customerGoal,120),budget:v.budget??undefined,preferredLocations:v.preferredLocations?.slice?.(0,8),propertyTypes:v.propertyTypes?.slice?.(0,8),bedrooms:v.bedrooms,hardRequirements:v.hardRequirements?.slice?.(0,8),softPreferences:v.softPreferences?.slice?.(0,8),intentScore:v.intentScore};}
function buildMessages(input:AnswerInput):AIMessage[]{return[{role:"system",content:SYSTEM_PROMPT},...(input.conversationSummary?[{role:"system" as const,content:`CONVERSATION_SUMMARY=${JSON.stringify(input.conversationSummary)}`}]:[]),...input.messages,{role:"user",content:`CONTEXT_KIND=${input.contextKind??"PROPERTY_SEARCH"}\nCURRENT_STATE=${JSON.stringify(compactIntent(input.intent))}\nVERIFIED_FACTS=${JSON.stringify(input.verifiedFacts)}\nAPPROVED_KNOWLEDGE=${JSON.stringify(input.approvedKnowledge??[])}`}];}
export function advisorMessages(input:AnswerInput):AIMessage[]{let compact=compactAnswerInput(input),messages=buildMessages(compact);if(bytes(messages)>64_000||Math.ceil(JSON.stringify(messages).length/4)>14_000){compact=compactAnswerInput(input,"aggressive");messages=buildMessages(compact)}return messages;}
export function answerContextMetrics(input:AnswerInput,model="unknown",stream=false){const compact=compactAnswerInput(input),messages=advisorMessages(compact),body={model,messages,temperature:0.2,max_tokens:1000,...(stream?{stream:true}:{})};return{messages,bodyBytes:bytes(body),estimatedInputTokens:Math.ceil(JSON.stringify(messages).length/4),messageCount:messages.length,recentHistoryCount:compact.messages.length,resultCount:compact.verifiedFacts.length,verifiedContextBytes:bytes(compact.verifiedFacts),contextBytes:bytes(messages)};}
