import * as assert from "node:assert/strict";
import { test } from "node:test";
import { advisorMessages, answerContextMetrics, compactAnswerInput } from "./ai-context";

function richUnit(index:number){return{id:`unit-${index}`,externalUnitId:`A-${index}`,unitType:"Apartment",bedrooms:2,bathrooms:2,builtUpArea:150+index,price:8_000_000+index,currency:"EGP",status:"AVAILABLE",deliveryDate:new Date("2028-01-01"),finishingType:"FINISHED",matchScore:90-index,matchReasons:["budget","location"],developer:{id:"dev",name:"Developer",portfolioProjects:Array.from({length:50},(_,i)=>({projectName:`History ${i}`,description:"x".repeat(1000)})),sourceMetadata:{secret:"forbidden"}},project:{id:"project",name:"Project",location:{name:"New Cairo"},amenities:Array.from({length:50},(_,i)=>({amenity:{canonicalName:`Amenity ${i}`}})),investmentProfile:{notes:"x".repeat(5000)},media:Array.from({length:30},()=>({url:"https://image"})),documents:Array.from({length:20},()=>({url:"https://document"})),knowledgeItems:Array.from({length:30},()=>({content:"x".repeat(1000)})),landmarks:[],competitorsFrom:[]},paymentPlans:Array.from({length:30},(_,i)=>({durationMonths:12+i,downPaymentAmount:1_000_000+i,totalPrice:9_000_000+i,currency:"EGP"})),offers:[{title:"Offer",discountAmount:100_000}]};}

test("eight rich Prisma results become five minimal property candidates",()=>{const input:any={messages:[{role:"user",content:"عايز شقة"}],intent:{language:"ar-EG"},verifiedFacts:Array.from({length:8},(_,i)=>richUnit(i)),contextKind:"PROPERTY_SEARCH"};const compact=compactAnswerInput(input);assert.equal(compact.verifiedFacts.length,5);const fact:any=compact.verifiedFacts[0];assert.equal(fact.unitCode,"A-0");assert.equal(fact.paymentPlan.durationMonths,41);assert.equal(fact.projectName,"Project");assert.equal(fact.developerName,"Developer");assert.equal(fact.location,"New Cairo");assert.equal("matchScore" in fact,false);assert.equal("matchReasons" in fact,false);const serialized=JSON.stringify(advisorMessages(compact));for(const forbidden of ["portfolioProjects","sourceMetadata","\"media\":","\"documents\":","knowledgeItems","investmentProfile","\"amenities\":"])assert.equal(serialized.includes(forbidden),false,forbidden);const metrics=answerContextMetrics(input,"openai/gpt-oss-120b",true);assert.ok(metrics.bodyBytes<64_000);assert.ok(metrics.estimatedInputTokens<14_000);});

test("project detail compaction selects only project facts and limited knowledge",()=>{const project:any={...richUnit(1).project,developer:richUnit(1).developer,shortDescriptionAr:"وصف",investmentProfile:{notes:"private oversized"}};const input:any={messages:[{role:"user",content:"تفاصيل المشروع"}],intent:{language:"ar-EG"},verifiedFacts:[project],approvedKnowledge:Array.from({length:20},(_,i)=>({category:"overview",content:`Fact ${i} ${"x".repeat(1000)}`,sourceText:"raw"})),contextKind:"PROJECT_DETAILS"};const compact=compactAnswerInput(input);assert.equal(compact.approvedKnowledge?.length,4);const serialized=JSON.stringify(compact);assert.equal(serialized.includes("portfolioProjects"),false);assert.equal(serialized.includes("sourceText"),false);});

test("long conversation sends structured summary plus eight recent messages",()=>{const input:any={messages:Array.from({length:40},(_,i)=>({role:i%2?"assistant":"user",content:`message-${i} ${"x".repeat(3000)}`})),intent:{language:"en"},verifiedFacts:[],conversationSummary:{customerGoal:"LIVING",budget:{max:10_000_000},recentConversation:Array(50).fill("duplicate")},contextKind:"PROPERTY_SEARCH"};const compact=compactAnswerInput(input);assert.equal(compact.messages.length,8);assert.equal(compact.messages.at(-1)?.content.startsWith("message-39"),true);assert.equal((compact.conversationSummary as any).customerGoal,"LIVING");assert.equal("recentConversation" in (compact.conversationSummary as any),false);});

test("query objective is included in compact answer state",()=>{const messages=advisorMessages({messages:[],intent:{language:"ar-EG",queryObjective:"CHEAPEST"},verifiedFacts:[],contextKind:"PROPERTY_SEARCH"});assert.match(messages.at(-1)?.content??"",/CHEAPEST/u);});
