export type AIMessage = { role: "user" | "assistant" | "system"; content: string };
export type StructuredIntent = {
  language: string;
  dialect?: "EGYPTIAN_ARABIC" | "MSA" | "ENGLISH" | "MIXED";
  purpose?: "LIVING" | "INVESTMENT";
  locations?: string[];
  propertyTypes?: string[];
  bedrooms?: number;
  bathrooms?: number;
  budgetMin?: number;
  budgetMax?: number;
  currency?: string;
  deliveryMaxYears?: number;
  maxDownPayment?: number;
  maxTravelMinutes?: number;
  hardRequirements?: string[];
  softPreferences?: string[];
  requestedMedia?: "IMAGES" | "BROCHURE" | "MAP";
  requestedProject?: string;
  exactRouteRequested?: boolean;
  routeOrigin?: string;
  routeDestination?: string;
  purchaseIntent?: number;
  contactName?: string;
  contactPhone?: string;
  budgetFlexible?: boolean;
  rejectedLocations?: string[];
  rejectedProjects?: string[];
  preferredDevelopers?: string[];
  preferredProjects?: string[];
  minimumArea?: number;
  maximumArea?: number;
  builtUpAreaMin?: number;
  builtUpAreaMax?: number;
  targetBuiltUpArea?: number;
  temporaryIntent?: "INVENTORY_AGGREGATION";
  aggregationDimension?: "BUILT_UP_AREA" | "PRICE" | "LOCATION" | "PROJECT" | "DEVELOPER" | "UNIT_TYPE" | "DELIVERY_DATE" | "PAYMENT_DURATION" | "BEDROOM_COUNT";
  familyRequirements?: string[];
  investmentRequirements?: string[];
  customerConcerns?: string[];
  extractionDegraded?: boolean;
};
export type AnswerInput = { messages: AIMessage[]; intent: StructuredIntent; verifiedFacts: unknown[]; approvedKnowledge?: unknown[]; requestId?: string; conversationId?: string };
export type AIHealth = { provider: string; configured: boolean; healthy: boolean; model: string | null; errorCode?: string };
export type AITraceContext = { requestId?: string; conversationId?: string };
export interface AIProvider {
  extractIntent(messages: AIMessage[], previous: StructuredIntent, context?: AITraceContext): Promise<StructuredIntent>;
  composeAnswer(input: AnswerInput): Promise<string>;
  streamAnswer(input: AnswerInput): AsyncIterable<string>;
  extractKnowledge(sourceText: string): Promise<Record<string, unknown>>;
  mapColumns(headers: string[], sampleRows: unknown[][], canonicalFields: string[]): Promise<Array<{ sourceColumn: string; canonicalField: string; confidence: number; explanation?: string }>>;
  health?(): Promise<AIHealth | AIHealth[]>;
}
