"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Building2, MapPin, Plus, Search } from "lucide-react";
import { adminApi, adminErrorMessage } from "@/lib/api";
import { CatalogDeleteButton } from "@/components/catalog-delete-button";
type Project = { id: string; name: string; nameAr?: string | null; adminStatus?: string; projectStatus?: string | null; developer: { id: string; name: string }; location?: { id: string; name: string } | null; _count?: { units: number; knowledgeItems: number } };
type Option = { id: string; name: string };
const makeSlug = (value: string) => value.toLowerCase().normalize("NFKD").replace(/[^\p{L}\p{N}]+/gu, "-").replace(/^-|-$/g, "");
export default function ProjectsPage() {
  const [items, setItems] = useState<Project[]>([]), [developers, setDevelopers] = useState<Option[]>([]), [locations, setLocations] = useState<Option[]>([]), [search, setSearch] = useState(""), [error, setError] = useState(""), [show, setShow] = useState(false);
  const load = () => Promise.all([adminApi.get<Project[]>("/catalog/projects"), adminApi.get<Option[]>("/catalog/developers"), adminApi.get<Option[]>("/locations")]).then(([p,d,l]) => { setItems(p); setDevelopers(d); setLocations(l); }).catch(error => setError(adminErrorMessage(error)));
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter(item => `${item.name} ${item.nameAr ?? ""} ${item.developer.name} ${item.location?.name ?? ""}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget), name = String(f.get("name") ?? "").trim(); try { await adminApi.post("/catalog/projects", { name, slug: makeSlug(name), developerId: f.get("developerId"), locationId: f.get("locationId") || undefined }); setShow(false); await load(); } catch (error) { setError(adminErrorMessage(error)); } }
  return <main className="mx-auto min-h-screen max-w-7xl p-4 sm:p-8" dir="rtl"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">المشروعات</h1><p className="mt-2 text-sm text-[#68756f]">البيانات الأساسية، الموقع، الاستثمار، الخدمات، الوسائط والمعرفة.</p></div><button onClick={() => setShow(true)} className="flex h-11 items-center gap-2 rounded-xl bg-forest px-5 text-sm font-bold text-white"><Plus size={17}/>إضافة مشروع</button></div>{error && <div className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}<label className="mt-6 flex h-11 max-w-md items-center gap-2 rounded-xl border bg-white px-3"><Search size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث عن مشروع أو مطور أو منطقة" className="w-full bg-transparent outline-none"/></label><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(item => <article key={item.id} className="flex min-h-64 flex-col rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Link href={`/admin/projects/${item.id}`} className="min-w-0 flex-1 rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-forest"><div className="flex items-center justify-between"><Building2 size={20} className="text-forest"/><span className="rounded-full bg-[#edf1ee] px-2 py-1 text-[11px] font-bold">{item.adminStatus || "DRAFT"}</span></div><h2 className="mt-4 truncate text-lg font-bold" dir="auto">{item.nameAr || item.name}</h2><p className="mt-1 text-sm text-[#68756f]" dir="auto">{item.developer.name}</p><p className="mt-3 flex items-center gap-1 text-xs"><MapPin size={13}/><span dir="auto">{item.location?.name || "لم تُحدد المنطقة"}</span></p><p className="mt-3 text-xs text-[#748079]">{item._count?.units ?? 0} وحدة · {item._count?.knowledgeItems ?? 0} معلومة</p></Link><div className="mt-4 flex items-center justify-between gap-3 border-t pt-3"><Link href={`/admin/projects/${item.id}`} className="text-xs font-bold text-forest hover:underline">فتح بيانات المشروع</Link><CatalogDeleteButton id={item.id} name={item.nameAr || item.name} resource="projects" entityLabel="المشروع" onDeleted={load}/></div></article>)}</div>{!error && filtered.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed bg-white p-8 text-center"><Building2 className="mx-auto text-[#8a9590]"/><p className="mt-3 font-bold">{items.length ? "لا يوجد مشروع مطابق للبحث." : "لم تتم إضافة مشروعات بعد."}</p></div> : null}
    {show && <div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4"><form onSubmit={create} className="w-full max-w-md rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">إضافة مشروع</h2><div className="mt-4 space-y-3"><input required name="name" placeholder="اسم المشروع" className="h-11 w-full rounded-xl border px-3"/><select required name="developerId" className="h-11 w-full rounded-xl border px-3"><option value="">اختر المطور</option>{developers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="locationId" className="h-11 w-full rounded-xl border px-3"><option value="">اختر المنطقة</option>{locations.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="flex gap-2"><button className="h-11 flex-1 rounded-xl bg-forest font-bold text-white">حفظ كمسودة</button><button type="button" onClick={() => setShow(false)} className="h-11 rounded-xl border px-5">إلغاء</button></div></div></form></div>}
  </main>;
}
