"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { adminApi, adminErrorMessage } from "@/lib/api";

type Unit = { id:string; externalUnitId:string; unitType?:string|null; building?:string|null; floor?:string|null; latitude?:number|string|null; longitude?:number|string|null; projectBuildingId?:string|null; projectZoneId?:string|null; masterPlanX?:number|string|null; masterPlanY?:number|string|null; masterPlanLocationStatus?:string|null };
type Gate = { id:string; name:string; nameAr?:string|null; gateNumber?:number|null; latitude?:number|string|null; longitude?:number|string|null; masterPlanX?:number|string|null; masterPlanY?:number|string|null; isMain?:boolean|null };
type Building = { id:string; name:string; nameAr?:string|null; code?:string|null; zoneId?:string|null; latitude?:number|string|null; longitude?:number|string|null; masterPlanX?:number|string|null; masterPlanY?:number|string|null; units?:Unit[] };
type Zone = { id:string; name:string; nameAr?:string|null; buildings?:Building[] };
type Media = { id:string; type:string; url:string };
type BoundaryPoint = { lat:number; lng:number };
type CalibrationAnchor = { x:number; y:number; latitude:number; longitude:number; boundaryIndex?:number };
type ProjectData = { gates?:Gate[]; zones?:Zone[]; buildings?:Building[]; boundaryGeoJson?:{type?:string;coordinates?:number[][][]}|null; boundarySource?:string|null; boundaryConfirmedAt?:string|null; masterPlanCalibration?:{anchors?:CalibrationAnchor[]}|null };
type UnitPage = { items:Unit[]; total:number };
type PendingPoint = { x:number; y:number } | null;

const label=(value:{name?:string|null;nameAr?:string|null})=>value.nameAr||value.name||"—";
const norm=(value:unknown)=>String(value??"").toLowerCase().normalize("NFKC").replace(/\s+/g," ").trim();

function boundaryPoints(value?:ProjectData["boundaryGeoJson"]):BoundaryPoint[]{
  const ring=value?.type==="Polygon"&&Array.isArray(value.coordinates?.[0])?value.coordinates![0]:[];
  const points=ring.map(pair=>({lng:Number(pair[0]),lat:Number(pair[1])})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));
  if(points.length>1&&points[0].lat===points.at(-1)?.lat&&points[0].lng===points.at(-1)?.lng)points.pop();
  return points;
}

function BoundaryPreview({points}:{points:BoundaryPoint[]}){
  if(points.length<2)return <div className="grid h-40 place-items-center rounded-2xl bg-[#f5f4ef] text-sm text-[#77827d]">أضف 3 نقاط GPS على الأقل لرسم حدود المشروع.</div>;
  const lats=points.map(p=>p.lat),lngs=points.map(p=>p.lng),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLng=Math.min(...lngs),maxLng=Math.max(...lngs),w=Math.max(.000001,maxLng-minLng),h=Math.max(.000001,maxLat-minLat);
  const pos=(p:BoundaryPoint)=>({x:12+((p.lng-minLng)/w)*276,y:148-((p.lat-minLat)/h)*130});
  return <svg viewBox="0 0 300 160" className="h-40 w-full rounded-2xl bg-[#f5f4ef]"><polygon points={points.map(p=>{const q=pos(p);return `${q.x},${q.y}`}).join(" ")} fill="rgba(24,59,51,.12)" stroke="currentColor" strokeWidth="2"/>{points.map((p,i)=>{const q=pos(p);return <g key={i}><circle cx={q.x} cy={q.y} r="4" fill="currentColor"/><text x={q.x+6} y={q.y-5} fontSize="9">{i+1}</text></g>})}</svg>;
}

export function ProjectSpatialEditor({projectId,media=[]}:{projectId:string;media?:Media[]}){
  const plan=useMemo(()=>media.find(x=>x.type==="MASTER_PLAN"),[media]);
  const imageRef=useRef<HTMLImageElement>(null);
  const [units,setUnits]=useState<Unit[]>([]),[gates,setGates]=useState<Gate[]>([]),[zones,setZones]=useState<Zone[]>([]),[buildings,setBuildings]=useState<Building[]>([]),[boundary,setBoundary]=useState<BoundaryPoint[]>([]),[anchors,setAnchors]=useState<CalibrationAnchor[]>([]);
  const [pending,setPending]=useState<PendingPoint>(null),[entityType,setEntityType]=useState<"BUILDING"|"UNITS"|"GATE">("BUILDING"),[selectedBuildingId,setSelectedBuildingId]=useState(""),[selectedGateId,setSelectedGateId]=useState(""),[selectedUnitIds,setSelectedUnitIds]=useState<string[]>([]),[unitFilter,setUnitFilter]=useState(""),[calibrationMode,setCalibrationMode]=useState(false),[boundaryIndex,setBoundaryIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState("");

  const fetchUnits=async()=>{const first=await adminApi.get<UnitPage>(`/catalog/units?projectId=${encodeURIComponent(projectId)}&page=1&pageSize=100`);const all=[...(first.items??[])];const pages=Math.ceil((first.total??all.length)/100);for(let page=2;page<=pages;page++){const next=await adminApi.get<UnitPage>(`/catalog/units?projectId=${encodeURIComponent(projectId)}&page=${page}&pageSize=100`);all.push(...(next.items??[]))}return all};
  const load=async()=>{try{const [allUnits,project]=await Promise.all([fetchUnits(),adminApi.get<ProjectData>(`/real-estate/projects/${projectId}`)]);setUnits(allUnits);setGates(project.gates??[]);setZones(project.zones??[]);setBuildings(project.buildings??project.zones?.flatMap(z=>z.buildings??[])??[]);setBoundary(boundaryPoints(project.boundaryGeoJson));setAnchors(Array.isArray(project.masterPlanCalibration?.anchors)?project.masterPlanCalibration!.anchors!:[]);}catch(e){setError(adminErrorMessage(e))}};
  useEffect(()=>{void load()},[projectId]);

  const normalizedPoint=(clientX:number,clientY:number)=>{if(!imageRef.current)return null;const r=imageRef.current.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(clientY-r.top)/r.height))}};
  const onPlanClick=(event:React.MouseEvent<HTMLImageElement>)=>{const point=normalizedPoint(event.clientX,event.clientY);if(!point)return;if(calibrationMode){const gps=boundary[boundaryIndex];if(!gps)return setError("اختر نقطة GPS من حدود المشروع أولاً.");setAnchors(current=>[...current.filter(a=>a.boundaryIndex!==boundaryIndex),{...point,latitude:gps.lat,longitude:gps.lng,boundaryIndex}]);return}setPending(point);setSelectedUnitIds([])};

  const saveCalibration=async()=>{if(anchors.length<3)return setError("المعايرة تحتاج 3 نقاط على الأقل بين الـ Master Plan وحدود GPS.");try{setBusy(true);setError("");await adminApi.patch(`/real-estate/projects/${projectId}/master-plan/calibration`,{anchors});setCalibrationMode(false);await load()}catch(e){setError(adminErrorMessage(e))}finally{setBusy(false)}};
  const toggleUnit=(id:string)=>setSelectedUnitIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
  const selectedBuilding=buildings.find(b=>b.id===selectedBuildingId);
  const filteredUnits=units.filter(u=>!unitFilter||norm(u.unitType).includes(norm(unitFilter))||norm(u.externalUnitId).includes(norm(unitFilter))||norm(u.building).includes(norm(unitFilter)));
  const autoSelectBuildingUnits=()=>{if(!selectedBuilding)return;const names=[selectedBuilding.name,selectedBuilding.nameAr,selectedBuilding.code].filter(Boolean).map(norm);setSelectedUnitIds(units.filter(u=>u.projectBuildingId===selectedBuilding.id||names.some(n=>n&&[u.building,u.externalUnitId].map(norm).some(v=>v.includes(n)))).map(u=>u.id))};

  const commitPoint=async()=>{if(!pending)return;try{setBusy(true);setError("");if(entityType==="GATE"){if(!selectedGateId)throw new Error("اختر البوابة.");await adminApi.patch(`/real-estate/gates/${selectedGateId}/master-plan-location`,pending)}else if(entityType==="BUILDING"){if(!selectedBuildingId)throw new Error("اختر المبنى.");await adminApi.patch(`/real-estate/buildings/${selectedBuildingId}/master-plan-location`,pending);if(selectedUnitIds.length)await adminApi.patch(`/real-estate/projects/${projectId}/master-plan/bulk-assign`,{...pending,buildingId:selectedBuildingId,unitIds:selectedUnitIds})}else{if(!selectedUnitIds.length)throw new Error("اختر وحدة واحدة على الأقل.");await adminApi.patch(`/real-estate/projects/${projectId}/master-plan/bulk-assign`,{...pending,unitIds:selectedUnitIds})}setPending(null);setSelectedUnitIds([]);await load()}catch(e){setError(adminErrorMessage(e))}finally{setBusy(false)}};

  async function addBuilding(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{setBusy(true);const item=await adminApi.post<Building>(`/real-estate/projects/${projectId}/buildings`,{name:String(form.get("name")||"").trim(),nameAr:String(form.get("nameAr")||"").trim()||undefined,code:String(form.get("code")||"").trim()||undefined,zoneId:String(form.get("zoneId")||"")||undefined});setSelectedBuildingId(item.id);event.currentTarget.reset();await load()}catch(e){setError(adminErrorMessage(e))}finally{setBusy(false)}}
  async function addGate(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{setBusy(true);const item=await adminApi.post<Gate>(`/real-estate/projects/${projectId}/gates`,{name:String(form.get("name")||"").trim(),nameAr:String(form.get("nameAr")||"").trim()||undefined,gateNumber:String(form.get("gateNumber")||"")?Number(form.get("gateNumber")):undefined,isMain:form.get("isMain")==="on"});setSelectedGateId(item.id);event.currentTarget.reset();await load()}catch(e){setError(adminErrorMessage(e))}finally{setBusy(false)}}
  const addBoundaryPoint=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),lat=Number(form.get("lat")),lng=Number(form.get("lng"));if(!Number.isFinite(lat)||!Number.isFinite(lng))return;setBoundary(p=>[...p,{lat,lng}]);event.currentTarget.reset()};
  const saveBoundary=async()=>{if(boundary.length<3)return setError("أضف 3 نقاط GPS على الأقل.");try{setBusy(true);await adminApi.patch(`/real-estate/projects/${projectId}/boundary`,{points:boundary,source:"GPS_MANUAL"});await load()}catch(e){setError(adminErrorMessage(e))}finally{setBusy(false)}};

  return <section className="mt-6 space-y-5" dir="rtl">
    <div className="rounded-[24px] border bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">حدود المشروع ومعايرة الـ Master Plan</h2><p className="mt-1 text-sm leading-7 text-[#68756f]">الـ GPS هو المرجع الحقيقي. بعد حفظ حدود الكمباوند، اربط 3 نقاط أو أكثر من الحدود بنفس الأماكن على صورة الـ Master Plan؛ بعدها أي مبنى أو وحدة تحطها على الصورة يطلع لها Latitude/Longitude تلقائيًا.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${anchors.length>=3?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>{anchors.length>=3?`تمت المعايرة · ${anchors.length} نقاط`:`المعايرة ناقصة · ${anchors.length}/3`}</span></div>
      <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_380px]"><BoundaryPreview points={boundary}/><div className="space-y-3"><form onSubmit={addBoundaryPoint} className="grid grid-cols-2 gap-2"><input name="lat" required type="number" step="any" placeholder="Latitude" className="h-11 rounded-xl border px-3"/><input name="lng" required type="number" step="any" placeholder="Longitude" className="h-11 rounded-xl border px-3"/><button className="col-span-2 h-11 rounded-xl border font-bold">+ إضافة نقطة GPS</button></form><div className="max-h-32 overflow-auto rounded-xl border">{boundary.map((p,i)=><div key={i} className="flex items-center justify-between border-b px-3 py-2 text-xs"><span dir="ltr">#{i+1} {p.lat.toFixed(7)}, {p.lng.toFixed(7)}</span><button type="button" onClick={()=>setBoundary(v=>v.filter((_,x)=>x!==i))} className="text-red-700">حذف</button></div>)}</div><button disabled={busy||boundary.length<3} type="button" onClick={saveBoundary} className="h-11 w-full rounded-xl bg-forest font-bold text-white disabled:opacity-40">حفظ حدود GPS</button></div></div>
    </div>

    <div className="rounded-[24px] border bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">التحديد على الـ Master Plan</h2><p className="mt-1 text-sm leading-7 text-[#68756f]">اضغط أي نقطة في المخطط. النظام هيسألك: دي بوابة، مبنى، ولا وحدة/مجموعة وحدات. بيانات الوحدات بتتسحب من المخزون الحالي.</p></div><button disabled={!plan||boundary.length<3} type="button" onClick={()=>{setCalibrationMode(v=>!v);setPending(null)}} className={`rounded-xl border px-4 py-2 text-sm font-bold ${calibrationMode?"bg-forest text-white":""}`}>{calibrationMode?"إنهاء وضع المعايرة":"معايرة GPS مع الصورة"}</button></div>
      {!plan?<div className="mt-4 rounded-2xl bg-[#f5f4ef] p-5 text-sm">ارفع صورة من نوع <b>MASTER_PLAN</b> للمشروع أولًا.</div>:<div className="mt-4 grid gap-4 xl:grid-cols-[320px_1fr]">
        <aside className="space-y-3">
          {calibrationMode?<div className="rounded-2xl border bg-[#faf9f5] p-4"><h3 className="font-bold">معايرة الصورة</h3><p className="mt-1 text-xs leading-6 text-[#68756f]">اختر نقطة من حدود GPS ثم اضغط مكانها المقابل على الـ Master Plan. كرر 3 مرات على الأقل وبنقاط بعيدة عن بعض.</p><select value={boundaryIndex} onChange={e=>setBoundaryIndex(Number(e.target.value))} className="mt-3 h-11 w-full rounded-xl border bg-white px-3">{boundary.map((p,i)=><option key={i} value={i}>نقطة #{i+1} · {p.lat.toFixed(5)}, {p.lng.toFixed(5)}</option>)}</select><div className="mt-3 space-y-1">{anchors.map((a,i)=><div key={i} className="flex justify-between rounded-lg bg-white px-2 py-2 text-xs"><span>GPS #{(a.boundaryIndex??0)+1}</span><span dir="ltr">{a.x.toFixed(3)}, {a.y.toFixed(3)}</span></div>)}</div><button disabled={busy||anchors.length<3} type="button" onClick={saveCalibration} className="mt-3 h-11 w-full rounded-xl bg-forest font-bold text-white disabled:opacity-40">حفظ المعايرة</button></div>:<div className="rounded-2xl border bg-[#faf9f5] p-4"><h3 className="font-bold">المخزون على المخطط</h3><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-white p-2"><b className="block text-base">{units.length}</b>وحدة</div><div className="rounded-xl bg-white p-2"><b className="block text-base">{buildings.length}</b>مبنى</div><div className="rounded-xl bg-white p-2"><b className="block text-base">{gates.length}</b>بوابة</div></div><p className="mt-3 text-xs leading-6 text-[#68756f]">الأفضل تحط المبنى مرة واحدة وتربط كل وحداته به بدل تحديد كل شقة لوحدها. لو في فيلا مستقلة أو وحدة إعادة بيع، تقدر تحددها مباشرة.</p></div>}
          <form onSubmit={addBuilding} className="grid gap-2 rounded-2xl border p-3"><b className="text-sm">+ مبنى جديد</b><input required name="name" placeholder="اسم المبنى" className="h-10 rounded-xl border px-3"/><div className="grid grid-cols-2 gap-2"><input name="nameAr" placeholder="الاسم العربي" className="h-10 rounded-xl border px-3"/><input name="code" placeholder="الكود" className="h-10 rounded-xl border px-3"/></div><select name="zoneId" className="h-10 rounded-xl border bg-white px-3"><option value="">بدون Zone</option>{zones.map(z=><option key={z.id} value={z.id}>{label(z)}</option>)}</select><button disabled={busy} className="h-10 rounded-xl border font-bold">إضافة مبنى</button></form>
          <form onSubmit={addGate} className="grid gap-2 rounded-2xl border p-3"><b className="text-sm">+ بوابة جديدة</b><input required name="name" placeholder="اسم البوابة" className="h-10 rounded-xl border px-3"/><div className="grid grid-cols-2 gap-2"><input name="nameAr" placeholder="العربي" className="h-10 rounded-xl border px-3"/><input name="gateNumber" type="number" min="1" placeholder="رقم" className="h-10 rounded-xl border px-3"/></div><label className="text-xs"><input name="isMain" type="checkbox"/> بوابة رئيسية</label><button disabled={busy} className="h-10 rounded-xl border font-bold">إضافة بوابة</button></form>
          {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
        </aside>
        <div className="relative overflow-auto rounded-2xl border bg-white"><div className="relative inline-block min-w-full"><img ref={imageRef} src={plan.url} alt="Master Plan" onClick={onPlanClick} draggable={false} className="block h-auto w-full cursor-crosshair select-none"/>
          {buildings.filter(b=>b.masterPlanX!=null&&b.masterPlanY!=null).map(b=><button key={b.id} type="button" onClick={e=>{e.stopPropagation();setSelectedBuildingId(b.id)}} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-xl bg-[#d7b46a] px-2 py-1 text-[10px] font-bold shadow" style={{left:`${Number(b.masterPlanX)*100}%`,top:`${Number(b.masterPlanY)*100}%`}}>{label(b)}</button>)}
          {units.filter(u=>u.masterPlanX!=null&&u.masterPlanY!=null&&!u.projectBuildingId).map(u=><button key={u.id} type="button" onClick={e=>{e.stopPropagation();setSelectedUnitIds([u.id])}} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full bg-forest px-2 py-1 text-[9px] text-white shadow" style={{left:`${Number(u.masterPlanX)*100}%`,top:`${Number(u.masterPlanY)*100}%`}}>{u.externalUnitId}</button>)}
          {gates.filter(g=>g.masterPlanX!=null&&g.masterPlanY!=null).map(g=><button key={g.id} type="button" onClick={e=>{e.stopPropagation();setSelectedGateId(g.id)}} className="absolute -translate-x-1/2 -translate-y-1/2 rounded bg-black px-2 py-1 text-[10px] text-white" style={{left:`${Number(g.masterPlanX)*100}%`,top:`${Number(g.masterPlanY)*100}%`}}>{label(g)}</button>)}
          {anchors.map((a,i)=><span key={`a-${i}`} className="pointer-events-none absolute grid h-6 w-6 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white bg-blue-600 text-[9px] font-bold text-white shadow" style={{left:`${a.x*100}%`,top:`${a.y*100}%`}}>G{(a.boundaryIndex??i)+1}</span>)}
        </div></div>
      </div>}
    </div>

    {pending&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4" onMouseDown={()=>setPending(null)}><div onMouseDown={e=>e.stopPropagation()} className="max-h-[88vh] w-full max-w-3xl overflow-auto rounded-[24px] bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-lg font-extrabold">إيه اللي موجود في النقطة دي؟</h3><p className="mt-1 text-xs text-[#68756f]" dir="ltr">X {pending.x.toFixed(4)} · Y {pending.y.toFixed(4)} {anchors.length>=3?"· GPS هيتحسب تلقائيًا":"· بدون GPS لحد ما تعمل المعايرة"}</p></div><button type="button" onClick={()=>setPending(null)} className="rounded-lg border px-3 py-1">✕</button></div>
      <div className="mt-4 grid grid-cols-3 gap-2">{([['BUILDING','مبنى'],['UNITS','وحدة / شقة / فيلا'],['GATE','بوابة']] as const).map(([v,t])=><button type="button" key={v} onClick={()=>setEntityType(v)} className={`rounded-xl border px-3 py-3 text-sm font-bold ${entityType===v?"bg-forest text-white":""}`}>{t}</button>)}</div>
      {entityType==="BUILDING"&&<div className="mt-4 space-y-3"><select value={selectedBuildingId} onChange={e=>{setSelectedBuildingId(e.target.value);setSelectedUnitIds([])}} className="h-12 w-full rounded-xl border bg-white px-3"><option value="">اختر المبنى</option>{buildings.map(b=><option key={b.id} value={b.id}>{label(b)} {b.code?`· ${b.code}`:""}</option>)}</select><div className="flex flex-wrap gap-2"><button type="button" onClick={autoSelectBuildingUnits} disabled={!selectedBuildingId} className="rounded-xl border px-3 py-2 text-sm font-bold">اختيار وحدات المبنى تلقائيًا</button><span className="rounded-xl bg-[#f3f1eb] px-3 py-2 text-sm">مختار {selectedUnitIds.length} وحدة</span></div><p className="text-xs leading-6 text-[#68756f]">لو المبنى فيه 10 أو 50 وحدة، اختارهم مرة واحدة. كلهم هيرتبطوا بالمبنى والنظام يقدر يستخدم موقع المبنى لكل الوحدات.</p></div>}
      {entityType==="GATE"&&<select value={selectedGateId} onChange={e=>setSelectedGateId(e.target.value)} className="mt-4 h-12 w-full rounded-xl border bg-white px-3"><option value="">اختر البوابة</option>{gates.map(g=><option key={g.id} value={g.id}>{label(g)}{g.isMain?" · رئيسية":""}</option>)}</select>}
      {(entityType==="UNITS"||entityType==="BUILDING")&&<div className="mt-4"><input value={unitFilter} onChange={e=>setUnitFilter(e.target.value)} placeholder="ابحث بكود الوحدة أو النوع أو المبنى..." className="h-11 w-full rounded-xl border px-3"/><div className="mt-2 max-h-72 overflow-auto rounded-xl border">{filteredUnits.map(u=><label key={u.id} className="flex cursor-pointer items-center gap-3 border-b px-3 py-2 text-sm hover:bg-[#faf9f5]"><input type="checkbox" checked={selectedUnitIds.includes(u.id)} onChange={()=>toggleUnit(u.id)}/><span className="font-bold" dir="ltr">{u.externalUnitId}</span><span className="text-[#68756f]">{u.unitType||"نوع غير محدد"}</span><span className="me-auto text-xs text-[#87918c]">{u.building||""}</span></label>)}</div></div>}
      <div className="mt-5 flex gap-2"><button disabled={busy} type="button" onClick={commitPoint} className="h-12 flex-1 rounded-xl bg-forest font-bold text-white disabled:opacity-40">تأكيد المكان</button><button type="button" onClick={()=>setPending(null)} className="h-12 rounded-xl border px-5">إلغاء</button></div>
    </div></div>}
  </section>;
}
