ALTER TABLE "ImportUnitChange" DROP CONSTRAINT "ImportUnitChange_unitId_fkey";
ALTER TABLE "ImportUnitChange" ALTER COLUMN "unitId" DROP NOT NULL;
ALTER TABLE "ImportUnitChange" ADD CONSTRAINT "ImportUnitChange_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Unit" ADD COLUMN "sourceMetadata" JSONB;
ALTER TABLE "DataImport" ADD COLUMN "rowsSkipped" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DataImport" ADD COLUMN "rowsFailed" INTEGER NOT NULL DEFAULT 0;
