import { BadRequestException, Body, ConflictException, Controller, Delete, Get, Param, Patch, Post, Req, UseGuards } from "@nestjs/common";
import { ApprovalStatus, LocationType } from "@prisma/client";
import { IsArray, IsBoolean, IsEnum, IsNumber, IsOptional, IsString, MaxLength } from "class-validator";
import { PrismaService } from "../database/prisma.service";
import { AdminAuthGuard } from "../auth/admin-auth.guard";
import { AuditService } from "../audit.service";

class LocationDto { @IsEnum(LocationType) type!: LocationType; @IsString() @MaxLength(120) name!: string; @IsString() @MaxLength(140) slug!: string; @IsOptional() @IsString() canonicalName?: string; @IsOptional() @IsString() nameAr?: string; @IsOptional() @IsString() nameEn?: string; @IsOptional() @IsString() formattedAddress?: string; @IsOptional() @IsString() source?: string; @IsOptional() @IsString() parentId?: string; @IsOptional() @IsNumber() latitude?: number; @IsOptional() @IsNumber() longitude?: number; @IsOptional() @IsString() googlePlaceId?: string; }
class UpdateLocationDto { @IsOptional() @IsEnum(LocationType) type?: LocationType; @IsOptional() @IsString() @MaxLength(120) name?: string; @IsOptional() @IsString() @MaxLength(140) slug?: string; @IsOptional() @IsString() canonicalName?: string; @IsOptional() @IsString() nameAr?: string; @IsOptional() @IsString() nameEn?: string; @IsOptional() @IsString() formattedAddress?: string; @IsOptional() @IsString() source?: string; @IsOptional() @IsString() parentId?: string; @IsOptional() @IsNumber() latitude?: number; @IsOptional() @IsNumber() longitude?: number; @IsOptional() @IsString() googlePlaceId?: string; }
class AliasDto { @IsString() value!: string; @IsOptional() @IsString() language?: string; }
class DistanceDto { @IsString() fromLocationId!: string; @IsString() toLocationId!: string; @IsNumber() distanceKm!: number; @IsOptional() @IsNumber() estimatedMinutes?: number; @IsOptional() @IsString() distanceType?: string; @IsOptional() @IsString() notes?: string; @IsOptional() @IsBoolean() isBidirectional?: boolean; }

@UseGuards(AdminAuthGuard)
@Controller("admin/locations")
export class LocationsController {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  private admin(req: any) { return req.admin?.id as string; }
  private async validateHierarchy(type: LocationType, parentId?: string, currentId?: string) {
    if (type === LocationType.COUNTRY && parentId) throw new BadRequestException("A country cannot have a parent location");
    if (type !== LocationType.COUNTRY && !parentId) throw new BadRequestException("A parent location is required");
    if (!parentId) return;
    if (parentId === currentId) throw new BadRequestException("A location cannot be its own parent");
    const parent = await this.prisma.location.findUniqueOrThrow({ where: { id: parentId } });
    const rank: Record<LocationType, number> = { COUNTRY: 0, GOVERNORATE: 1, CITY: 2, AREA: 3, SUBAREA: 4 };
    if (rank[parent.type] >= rank[type]) throw new BadRequestException("Parent location must be a higher geographic level");
    let cursor: string | null | undefined = parent.parentId;
    while (cursor) { if (cursor === currentId) throw new BadRequestException("Location hierarchy cannot contain a cycle"); const ancestor: { parentId: string | null } | null = await this.prisma.location.findUnique({ where: { id: cursor }, select: { parentId: true } }); cursor = ancestor?.parentId; }
  }
  @Get() list() { return this.prisma.location.findMany({ include: { aliases: true, parent: { select: { id: true, name: true, type: true } } }, orderBy: [{ type: "asc" }, { name: "asc" }] }); }
  @Post() async create(@Body() body: LocationDto, @Req() req: any) { await this.validateHierarchy(body.type, body.parentId); const existing = await this.prisma.location.findFirst({ where: { type: body.type, name: { equals: body.name.trim(), mode: "insensitive" }, parentId: body.parentId || null } }); if (existing) return existing; const item = await this.prisma.location.create({ data: body }); await this.audit.record(this.admin(req), "LOCATION_CREATED", "Location", item.id, body); return item; }
  @Patch(":id") async update(@Param("id") id: string, @Body() body: UpdateLocationDto, @Req() req: any) { const current = await this.prisma.location.findUniqueOrThrow({ where: { id } }); await this.validateHierarchy(body.type ?? current.type, body.parentId ?? current.parentId ?? undefined, id); const item = await this.prisma.location.update({ where: { id }, data: body }); await this.audit.record(this.admin(req), "LOCATION_UPDATED", "Location", id, body); return item; }
  @Delete(":id") async remove(@Param("id") id: string, @Req() req: any) { const dependencies = await this.prisma.location.findUniqueOrThrow({ where: { id }, select: { _count: { select: { children: true, projects: true, distancesFrom: true, distancesTo: true } } } }); if (dependencies._count.children || dependencies._count.projects || dependencies._count.distancesFrom || dependencies._count.distancesTo) throw new ConflictException("Location has dependent projects, child locations or distances and cannot be deleted safely"); await this.prisma.location.delete({ where: { id } }); await this.audit.record(this.admin(req), "LOCATION_DELETED", "Location", id); return { deleted: true }; }
  @Post(":id/aliases") async alias(@Param("id") locationId: string, @Body() body: AliasDto, @Req() req: any) { const normalizedValue = body.value.toLowerCase().normalize("NFKD").replace(/[^\p{L}\p{N}]+/gu, " ").trim(); const item = await this.prisma.locationAlias.create({ data: { locationId, value: body.value, normalizedValue, language: body.language, approvalStatus: ApprovalStatus.APPROVED } }); await this.audit.record(this.admin(req), "LOCATION_ALIAS_CREATED", "LocationAlias", item.id); return item; }
  @Delete("aliases/:aliasId") async removeAlias(@Param("aliasId") id: string, @Req() req: any) { await this.prisma.locationAlias.delete({ where: { id } }); await this.audit.record(this.admin(req), "LOCATION_ALIAS_DELETED", "LocationAlias", id); return { deleted: true }; }
  @Get("distances/all") distances() { return this.prisma.locationDistance.findMany({ include: { from: true, to: true }, orderBy: { distanceKm: "asc" } }); }
  @Post("distances") async distance(@Body() body: DistanceDto, @Req() req: any) { if (body.fromLocationId === body.toLocationId) throw new BadRequestException("Distance locations must be different"); const verifiedByAdminId = this.admin(req); const item = await this.prisma.$transaction(async tx => { const first = await tx.locationDistance.upsert({ where: { fromLocationId_toLocationId: { fromLocationId: body.fromLocationId, toLocationId: body.toLocationId } }, create: { ...body, distanceType: body.distanceType || "ADMIN_VERIFIED", verifiedAt: new Date(), verifiedByAdminId }, update: { ...body, verifiedAt: new Date(), verifiedByAdminId } }); if (body.isBidirectional !== false) await tx.locationDistance.upsert({ where: { fromLocationId_toLocationId: { fromLocationId: body.toLocationId, toLocationId: body.fromLocationId } }, create: { ...body, fromLocationId: body.toLocationId, toLocationId: body.fromLocationId, distanceType: body.distanceType || "ADMIN_VERIFIED", verifiedAt: new Date(), verifiedByAdminId }, update: { distanceKm: body.distanceKm, estimatedMinutes: body.estimatedMinutes, notes: body.notes, verifiedAt: new Date(), verifiedByAdminId } }); return first; }); await this.audit.record(this.admin(req), "LOCATION_DISTANCE_SAVED", "LocationDistance", item.id); return item; }
}
